on:
  release:
    types:
      - created

name: prd

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm ci
      - name: Prd
        run: npm run build
        env:
          BUILDER_SERVER_URL: https://builder-api.decentraland.org
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_PRD }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET_PRD }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_PRD }}
          S3_REGION: us-east-1
          S3_UPLOAD_CONCURRENCY: 20
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
